//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPV_EncuestasSena.ServicioEncuestasSena {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OS_ConsultarTiposDocumento", Namespace="http://schemas.datacontract.org/2004/07/HPV_Entidades.IncripcionEncuestasWS")]
    [System.SerializableAttribute()]
    public partial class OS_ConsultarTiposDocumento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HPV_EncuestasSena.ServicioEncuestasSena.OE_TiposDocumento[] ListaTiposDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HPV_EncuestasSena.ServicioEncuestasSena.Respuesta RespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HPV_EncuestasSena.ServicioEncuestasSena.OE_TiposDocumento[] ListaTiposDocumento {
            get {
                return this.ListaTiposDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaTiposDocumentoField, value) != true)) {
                    this.ListaTiposDocumentoField = value;
                    this.RaisePropertyChanged("ListaTiposDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HPV_EncuestasSena.ServicioEncuestasSena.Respuesta Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaField, value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/HPV_Entidades.General")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OE_TiposDocumento", Namespace="http://schemas.datacontract.org/2004/07/HPV_Entidades.EncuestasSena")]
    [System.SerializableAttribute()]
    public partial class OE_TiposDocumento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OS_CrearDatosBasicos", Namespace="http://schemas.datacontract.org/2004/07/HPV_Entidades.IncripcionEncuestasWS")]
    [System.SerializableAttribute()]
    public partial class OS_CrearDatosBasicos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HPV_EncuestasSena.ServicioEncuestasSena.Respuesta RespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HPV_EncuestasSena.ServicioEncuestasSena.OE_UsuarioEncuesta UsuarioEncuestaSenaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HPV_EncuestasSena.ServicioEncuestasSena.Respuesta Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaField, value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HPV_EncuestasSena.ServicioEncuestasSena.OE_UsuarioEncuesta UsuarioEncuestaSena {
            get {
                return this.UsuarioEncuestaSenaField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioEncuestaSenaField, value) != true)) {
                    this.UsuarioEncuestaSenaField = value;
                    this.RaisePropertyChanged("UsuarioEncuestaSena");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OE_UsuarioEncuesta", Namespace="http://schemas.datacontract.org/2004/07/HPV_Entidades.EncuestasSena")]
    [System.SerializableAttribute()]
    public partial class OE_UsuarioEncuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsecutivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EsJovenEnAccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEncuestaPresentarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsusarioEncuestaSenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Consecutivo {
            get {
                return this.ConsecutivoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsecutivoField, value) != true)) {
                    this.ConsecutivoField = value;
                    this.RaisePropertyChanged("Consecutivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EsJovenEnAccion {
            get {
                return this.EsJovenEnAccionField;
            }
            set {
                if ((this.EsJovenEnAccionField.Equals(value) != true)) {
                    this.EsJovenEnAccionField = value;
                    this.RaisePropertyChanged("EsJovenEnAccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEncuestaPresentar {
            get {
                return this.IdEncuestaPresentarField;
            }
            set {
                if ((this.IdEncuestaPresentarField.Equals(value) != true)) {
                    this.IdEncuestaPresentarField = value;
                    this.RaisePropertyChanged("IdEncuestaPresentar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsusarioEncuestaSena {
            get {
                return this.IdUsusarioEncuestaSenaField;
            }
            set {
                if ((this.IdUsusarioEncuestaSenaField.Equals(value) != true)) {
                    this.IdUsusarioEncuestaSenaField = value;
                    this.RaisePropertyChanged("IdUsusarioEncuestaSena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellido {
            get {
                return this.PrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerApellidoField, value) != true)) {
                    this.PrimerApellidoField = value;
                    this.RaisePropertyChanged("PrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellido {
            get {
                return this.SegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoField, value) != true)) {
                    this.SegundoApellidoField = value;
                    this.RaisePropertyChanged("SegundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento {
            get {
                return this.TipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDocumentoField, value) != true)) {
                    this.TipoDocumentoField = value;
                    this.RaisePropertyChanged("TipoDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OS_Consultar_Preguntas", Namespace="http://schemas.datacontract.org/2004/07/HPV_Entidades.IncripcionEncuestasWS")]
    [System.SerializableAttribute()]
    public partial class OS_Consultar_Preguntas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HPV_EncuestasSena.ServicioEncuestasSena.OE_Pregunta[] PreguntasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HPV_EncuestasSena.ServicioEncuestasSena.Respuesta RespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HPV_EncuestasSena.ServicioEncuestasSena.OE_Pregunta[] Preguntas {
            get {
                return this.PreguntasField;
            }
            set {
                if ((object.ReferenceEquals(this.PreguntasField, value) != true)) {
                    this.PreguntasField = value;
                    this.RaisePropertyChanged("Preguntas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HPV_EncuestasSena.ServicioEncuestasSena.Respuesta Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaField, value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OE_Pregunta", Namespace="http://schemas.datacontract.org/2004/07/HPV_Entidades.EncuestasSena")]
    [System.SerializableAttribute()]
    public partial class OE_Pregunta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEncuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPreguntaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroPreguntaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreguntaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HPV_EncuestasSena.ServicioEncuestasSena.OE_Respuesta[] RespuestasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEncuesta {
            get {
                return this.IdEncuestaField;
            }
            set {
                if ((this.IdEncuestaField.Equals(value) != true)) {
                    this.IdEncuestaField = value;
                    this.RaisePropertyChanged("IdEncuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPregunta {
            get {
                return this.IdPreguntaField;
            }
            set {
                if ((this.IdPreguntaField.Equals(value) != true)) {
                    this.IdPreguntaField = value;
                    this.RaisePropertyChanged("IdPregunta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroPregunta {
            get {
                return this.NumeroPreguntaField;
            }
            set {
                if ((this.NumeroPreguntaField.Equals(value) != true)) {
                    this.NumeroPreguntaField = value;
                    this.RaisePropertyChanged("NumeroPregunta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pregunta {
            get {
                return this.PreguntaField;
            }
            set {
                if ((object.ReferenceEquals(this.PreguntaField, value) != true)) {
                    this.PreguntaField = value;
                    this.RaisePropertyChanged("Pregunta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HPV_EncuestasSena.ServicioEncuestasSena.OE_Respuesta[] Respuestas {
            get {
                return this.RespuestasField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestasField, value) != true)) {
                    this.RespuestasField = value;
                    this.RaisePropertyChanged("Respuestas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OE_Respuesta", Namespace="http://schemas.datacontract.org/2004/07/HPV_Entidades.EncuestasSena")]
    [System.SerializableAttribute()]
    public partial class OE_Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPreguntaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LetraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SeleccionadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPregunta {
            get {
                return this.IdPreguntaField;
            }
            set {
                if ((this.IdPreguntaField.Equals(value) != true)) {
                    this.IdPreguntaField = value;
                    this.RaisePropertyChanged("IdPregunta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRespuesta {
            get {
                return this.IdRespuestaField;
            }
            set {
                if ((this.IdRespuestaField.Equals(value) != true)) {
                    this.IdRespuestaField = value;
                    this.RaisePropertyChanged("IdRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Letra {
            get {
                return this.LetraField;
            }
            set {
                if ((object.ReferenceEquals(this.LetraField, value) != true)) {
                    this.LetraField = value;
                    this.RaisePropertyChanged("Letra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaField, value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Seleccionado {
            get {
                return this.SeleccionadoField;
            }
            set {
                if ((this.SeleccionadoField.Equals(value) != true)) {
                    this.SeleccionadoField = value;
                    this.RaisePropertyChanged("Seleccionado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OS_Guardar_Encuesta", Namespace="http://schemas.datacontract.org/2004/07/HPV_Entidades.IncripcionEncuestasWS")]
    [System.SerializableAttribute()]
    public partial class OS_Guardar_Encuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HPV_EncuestasSena.ServicioEncuestasSena.Respuesta RespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HPV_EncuestasSena.ServicioEncuestasSena.OE_RespuestasEncuesta[] RespuestasEncuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HPV_EncuestasSena.ServicioEncuestasSena.Respuesta Respuesta {
            get {
                return this.RespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestaField, value) != true)) {
                    this.RespuestaField = value;
                    this.RaisePropertyChanged("Respuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HPV_EncuestasSena.ServicioEncuestasSena.OE_RespuestasEncuesta[] RespuestasEncuesta {
            get {
                return this.RespuestasEncuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.RespuestasEncuestaField, value) != true)) {
                    this.RespuestasEncuestaField = value;
                    this.RaisePropertyChanged("RespuestasEncuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OE_RespuestasEncuesta", Namespace="http://schemas.datacontract.org/2004/07/HPV_Entidades.EncuestasSena")]
    [System.SerializableAttribute()]
    public partial class OE_RespuestasEncuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodEncuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodPreguntaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodRespuestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodUsuarioSenaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodEncuesta {
            get {
                return this.CodEncuestaField;
            }
            set {
                if ((this.CodEncuestaField.Equals(value) != true)) {
                    this.CodEncuestaField = value;
                    this.RaisePropertyChanged("CodEncuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodPregunta {
            get {
                return this.CodPreguntaField;
            }
            set {
                if ((this.CodPreguntaField.Equals(value) != true)) {
                    this.CodPreguntaField = value;
                    this.RaisePropertyChanged("CodPregunta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodRespuesta {
            get {
                return this.CodRespuestaField;
            }
            set {
                if ((this.CodRespuestaField.Equals(value) != true)) {
                    this.CodRespuestaField = value;
                    this.RaisePropertyChanged("CodRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodUsuarioSena {
            get {
                return this.CodUsuarioSenaField;
            }
            set {
                if ((this.CodUsuarioSenaField.Equals(value) != true)) {
                    this.CodUsuarioSenaField = value;
                    this.RaisePropertyChanged("CodUsuarioSena");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioEncuestasSena.IHPVServicioEncuestas")]
    public interface IHPVServicioEncuestas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHPVServicioEncuestas/ObtenerTiposDocumento", ReplyAction="http://tempuri.org/IHPVServicioEncuestas/ObtenerTiposDocumentoResponse")]
        HPV_EncuestasSena.ServicioEncuestasSena.OS_ConsultarTiposDocumento ObtenerTiposDocumento();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHPVServicioEncuestas/ObtenerTiposDocumento", ReplyAction="http://tempuri.org/IHPVServicioEncuestas/ObtenerTiposDocumentoResponse")]
        System.IAsyncResult BeginObtenerTiposDocumento(System.AsyncCallback callback, object asyncState);
        
        HPV_EncuestasSena.ServicioEncuestasSena.OS_ConsultarTiposDocumento EndObtenerTiposDocumento(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHPVServicioEncuestas/CrearDatosBasicos", ReplyAction="http://tempuri.org/IHPVServicioEncuestas/CrearDatosBasicosResponse")]
        HPV_EncuestasSena.ServicioEncuestasSena.OS_CrearDatosBasicos CrearDatosBasicos(HPV_EncuestasSena.ServicioEncuestasSena.OS_CrearDatosBasicos UsuarioSena);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHPVServicioEncuestas/CrearDatosBasicos", ReplyAction="http://tempuri.org/IHPVServicioEncuestas/CrearDatosBasicosResponse")]
        System.IAsyncResult BeginCrearDatosBasicos(HPV_EncuestasSena.ServicioEncuestasSena.OS_CrearDatosBasicos UsuarioSena, System.AsyncCallback callback, object asyncState);
        
        HPV_EncuestasSena.ServicioEncuestasSena.OS_CrearDatosBasicos EndCrearDatosBasicos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHPVServicioEncuestas/ObtenerPreguntas", ReplyAction="http://tempuri.org/IHPVServicioEncuestas/ObtenerPreguntasResponse")]
        HPV_EncuestasSena.ServicioEncuestasSena.OS_Consultar_Preguntas ObtenerPreguntas(int IdEncuesta);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHPVServicioEncuestas/ObtenerPreguntas", ReplyAction="http://tempuri.org/IHPVServicioEncuestas/ObtenerPreguntasResponse")]
        System.IAsyncResult BeginObtenerPreguntas(int IdEncuesta, System.AsyncCallback callback, object asyncState);
        
        HPV_EncuestasSena.ServicioEncuestasSena.OS_Consultar_Preguntas EndObtenerPreguntas(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHPVServicioEncuestas/GuardarRespuestasEncuesta", ReplyAction="http://tempuri.org/IHPVServicioEncuestas/GuardarRespuestasEncuestaResponse")]
        HPV_EncuestasSena.ServicioEncuestasSena.OS_CrearDatosBasicos GuardarRespuestasEncuesta(HPV_EncuestasSena.ServicioEncuestasSena.OS_Guardar_Encuesta respuestas);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IHPVServicioEncuestas/GuardarRespuestasEncuesta", ReplyAction="http://tempuri.org/IHPVServicioEncuestas/GuardarRespuestasEncuestaResponse")]
        System.IAsyncResult BeginGuardarRespuestasEncuesta(HPV_EncuestasSena.ServicioEncuestasSena.OS_Guardar_Encuesta respuestas, System.AsyncCallback callback, object asyncState);
        
        HPV_EncuestasSena.ServicioEncuestasSena.OS_CrearDatosBasicos EndGuardarRespuestasEncuesta(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHPVServicioEncuestasChannel : HPV_EncuestasSena.ServicioEncuestasSena.IHPVServicioEncuestas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObtenerTiposDocumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObtenerTiposDocumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HPV_EncuestasSena.ServicioEncuestasSena.OS_ConsultarTiposDocumento Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HPV_EncuestasSena.ServicioEncuestasSena.OS_ConsultarTiposDocumento)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrearDatosBasicosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CrearDatosBasicosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HPV_EncuestasSena.ServicioEncuestasSena.OS_CrearDatosBasicos Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HPV_EncuestasSena.ServicioEncuestasSena.OS_CrearDatosBasicos)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObtenerPreguntasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObtenerPreguntasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HPV_EncuestasSena.ServicioEncuestasSena.OS_Consultar_Preguntas Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HPV_EncuestasSena.ServicioEncuestasSena.OS_Consultar_Preguntas)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GuardarRespuestasEncuestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GuardarRespuestasEncuestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public HPV_EncuestasSena.ServicioEncuestasSena.OS_CrearDatosBasicos Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((HPV_EncuestasSena.ServicioEncuestasSena.OS_CrearDatosBasicos)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HPVServicioEncuestasClient : System.ServiceModel.ClientBase<HPV_EncuestasSena.ServicioEncuestasSena.IHPVServicioEncuestas>, HPV_EncuestasSena.ServicioEncuestasSena.IHPVServicioEncuestas {
        
        private BeginOperationDelegate onBeginObtenerTiposDocumentoDelegate;
        
        private EndOperationDelegate onEndObtenerTiposDocumentoDelegate;
        
        private System.Threading.SendOrPostCallback onObtenerTiposDocumentoCompletedDelegate;
        
        private BeginOperationDelegate onBeginCrearDatosBasicosDelegate;
        
        private EndOperationDelegate onEndCrearDatosBasicosDelegate;
        
        private System.Threading.SendOrPostCallback onCrearDatosBasicosCompletedDelegate;
        
        private BeginOperationDelegate onBeginObtenerPreguntasDelegate;
        
        private EndOperationDelegate onEndObtenerPreguntasDelegate;
        
        private System.Threading.SendOrPostCallback onObtenerPreguntasCompletedDelegate;
        
        private BeginOperationDelegate onBeginGuardarRespuestasEncuestaDelegate;
        
        private EndOperationDelegate onEndGuardarRespuestasEncuestaDelegate;
        
        private System.Threading.SendOrPostCallback onGuardarRespuestasEncuestaCompletedDelegate;
        
        public HPVServicioEncuestasClient() {
        }
        
        public HPVServicioEncuestasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HPVServicioEncuestasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HPVServicioEncuestasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HPVServicioEncuestasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<ObtenerTiposDocumentoCompletedEventArgs> ObtenerTiposDocumentoCompleted;
        
        public event System.EventHandler<CrearDatosBasicosCompletedEventArgs> CrearDatosBasicosCompleted;
        
        public event System.EventHandler<ObtenerPreguntasCompletedEventArgs> ObtenerPreguntasCompleted;
        
        public event System.EventHandler<GuardarRespuestasEncuestaCompletedEventArgs> GuardarRespuestasEncuestaCompleted;
        
        public HPV_EncuestasSena.ServicioEncuestasSena.OS_ConsultarTiposDocumento ObtenerTiposDocumento() {
            return base.Channel.ObtenerTiposDocumento();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginObtenerTiposDocumento(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObtenerTiposDocumento(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HPV_EncuestasSena.ServicioEncuestasSena.OS_ConsultarTiposDocumento EndObtenerTiposDocumento(System.IAsyncResult result) {
            return base.Channel.EndObtenerTiposDocumento(result);
        }
        
        private System.IAsyncResult OnBeginObtenerTiposDocumento(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginObtenerTiposDocumento(callback, asyncState);
        }
        
        private object[] OnEndObtenerTiposDocumento(System.IAsyncResult result) {
            HPV_EncuestasSena.ServicioEncuestasSena.OS_ConsultarTiposDocumento retVal = this.EndObtenerTiposDocumento(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObtenerTiposDocumentoCompleted(object state) {
            if ((this.ObtenerTiposDocumentoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObtenerTiposDocumentoCompleted(this, new ObtenerTiposDocumentoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObtenerTiposDocumentoAsync() {
            this.ObtenerTiposDocumentoAsync(null);
        }
        
        public void ObtenerTiposDocumentoAsync(object userState) {
            if ((this.onBeginObtenerTiposDocumentoDelegate == null)) {
                this.onBeginObtenerTiposDocumentoDelegate = new BeginOperationDelegate(this.OnBeginObtenerTiposDocumento);
            }
            if ((this.onEndObtenerTiposDocumentoDelegate == null)) {
                this.onEndObtenerTiposDocumentoDelegate = new EndOperationDelegate(this.OnEndObtenerTiposDocumento);
            }
            if ((this.onObtenerTiposDocumentoCompletedDelegate == null)) {
                this.onObtenerTiposDocumentoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObtenerTiposDocumentoCompleted);
            }
            base.InvokeAsync(this.onBeginObtenerTiposDocumentoDelegate, null, this.onEndObtenerTiposDocumentoDelegate, this.onObtenerTiposDocumentoCompletedDelegate, userState);
        }
        
        public HPV_EncuestasSena.ServicioEncuestasSena.OS_CrearDatosBasicos CrearDatosBasicos(HPV_EncuestasSena.ServicioEncuestasSena.OS_CrearDatosBasicos UsuarioSena) {
            return base.Channel.CrearDatosBasicos(UsuarioSena);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCrearDatosBasicos(HPV_EncuestasSena.ServicioEncuestasSena.OS_CrearDatosBasicos UsuarioSena, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCrearDatosBasicos(UsuarioSena, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HPV_EncuestasSena.ServicioEncuestasSena.OS_CrearDatosBasicos EndCrearDatosBasicos(System.IAsyncResult result) {
            return base.Channel.EndCrearDatosBasicos(result);
        }
        
        private System.IAsyncResult OnBeginCrearDatosBasicos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HPV_EncuestasSena.ServicioEncuestasSena.OS_CrearDatosBasicos UsuarioSena = ((HPV_EncuestasSena.ServicioEncuestasSena.OS_CrearDatosBasicos)(inValues[0]));
            return this.BeginCrearDatosBasicos(UsuarioSena, callback, asyncState);
        }
        
        private object[] OnEndCrearDatosBasicos(System.IAsyncResult result) {
            HPV_EncuestasSena.ServicioEncuestasSena.OS_CrearDatosBasicos retVal = this.EndCrearDatosBasicos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCrearDatosBasicosCompleted(object state) {
            if ((this.CrearDatosBasicosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CrearDatosBasicosCompleted(this, new CrearDatosBasicosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CrearDatosBasicosAsync(HPV_EncuestasSena.ServicioEncuestasSena.OS_CrearDatosBasicos UsuarioSena) {
            this.CrearDatosBasicosAsync(UsuarioSena, null);
        }
        
        public void CrearDatosBasicosAsync(HPV_EncuestasSena.ServicioEncuestasSena.OS_CrearDatosBasicos UsuarioSena, object userState) {
            if ((this.onBeginCrearDatosBasicosDelegate == null)) {
                this.onBeginCrearDatosBasicosDelegate = new BeginOperationDelegate(this.OnBeginCrearDatosBasicos);
            }
            if ((this.onEndCrearDatosBasicosDelegate == null)) {
                this.onEndCrearDatosBasicosDelegate = new EndOperationDelegate(this.OnEndCrearDatosBasicos);
            }
            if ((this.onCrearDatosBasicosCompletedDelegate == null)) {
                this.onCrearDatosBasicosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCrearDatosBasicosCompleted);
            }
            base.InvokeAsync(this.onBeginCrearDatosBasicosDelegate, new object[] {
                        UsuarioSena}, this.onEndCrearDatosBasicosDelegate, this.onCrearDatosBasicosCompletedDelegate, userState);
        }
        
        public HPV_EncuestasSena.ServicioEncuestasSena.OS_Consultar_Preguntas ObtenerPreguntas(int IdEncuesta) {
            return base.Channel.ObtenerPreguntas(IdEncuesta);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginObtenerPreguntas(int IdEncuesta, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObtenerPreguntas(IdEncuesta, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HPV_EncuestasSena.ServicioEncuestasSena.OS_Consultar_Preguntas EndObtenerPreguntas(System.IAsyncResult result) {
            return base.Channel.EndObtenerPreguntas(result);
        }
        
        private System.IAsyncResult OnBeginObtenerPreguntas(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int IdEncuesta = ((int)(inValues[0]));
            return this.BeginObtenerPreguntas(IdEncuesta, callback, asyncState);
        }
        
        private object[] OnEndObtenerPreguntas(System.IAsyncResult result) {
            HPV_EncuestasSena.ServicioEncuestasSena.OS_Consultar_Preguntas retVal = this.EndObtenerPreguntas(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObtenerPreguntasCompleted(object state) {
            if ((this.ObtenerPreguntasCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObtenerPreguntasCompleted(this, new ObtenerPreguntasCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObtenerPreguntasAsync(int IdEncuesta) {
            this.ObtenerPreguntasAsync(IdEncuesta, null);
        }
        
        public void ObtenerPreguntasAsync(int IdEncuesta, object userState) {
            if ((this.onBeginObtenerPreguntasDelegate == null)) {
                this.onBeginObtenerPreguntasDelegate = new BeginOperationDelegate(this.OnBeginObtenerPreguntas);
            }
            if ((this.onEndObtenerPreguntasDelegate == null)) {
                this.onEndObtenerPreguntasDelegate = new EndOperationDelegate(this.OnEndObtenerPreguntas);
            }
            if ((this.onObtenerPreguntasCompletedDelegate == null)) {
                this.onObtenerPreguntasCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObtenerPreguntasCompleted);
            }
            base.InvokeAsync(this.onBeginObtenerPreguntasDelegate, new object[] {
                        IdEncuesta}, this.onEndObtenerPreguntasDelegate, this.onObtenerPreguntasCompletedDelegate, userState);
        }
        
        public HPV_EncuestasSena.ServicioEncuestasSena.OS_CrearDatosBasicos GuardarRespuestasEncuesta(HPV_EncuestasSena.ServicioEncuestasSena.OS_Guardar_Encuesta respuestas) {
            return base.Channel.GuardarRespuestasEncuesta(respuestas);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGuardarRespuestasEncuesta(HPV_EncuestasSena.ServicioEncuestasSena.OS_Guardar_Encuesta respuestas, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGuardarRespuestasEncuesta(respuestas, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public HPV_EncuestasSena.ServicioEncuestasSena.OS_CrearDatosBasicos EndGuardarRespuestasEncuesta(System.IAsyncResult result) {
            return base.Channel.EndGuardarRespuestasEncuesta(result);
        }
        
        private System.IAsyncResult OnBeginGuardarRespuestasEncuesta(object[] inValues, System.AsyncCallback callback, object asyncState) {
            HPV_EncuestasSena.ServicioEncuestasSena.OS_Guardar_Encuesta respuestas = ((HPV_EncuestasSena.ServicioEncuestasSena.OS_Guardar_Encuesta)(inValues[0]));
            return this.BeginGuardarRespuestasEncuesta(respuestas, callback, asyncState);
        }
        
        private object[] OnEndGuardarRespuestasEncuesta(System.IAsyncResult result) {
            HPV_EncuestasSena.ServicioEncuestasSena.OS_CrearDatosBasicos retVal = this.EndGuardarRespuestasEncuesta(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGuardarRespuestasEncuestaCompleted(object state) {
            if ((this.GuardarRespuestasEncuestaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GuardarRespuestasEncuestaCompleted(this, new GuardarRespuestasEncuestaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GuardarRespuestasEncuestaAsync(HPV_EncuestasSena.ServicioEncuestasSena.OS_Guardar_Encuesta respuestas) {
            this.GuardarRespuestasEncuestaAsync(respuestas, null);
        }
        
        public void GuardarRespuestasEncuestaAsync(HPV_EncuestasSena.ServicioEncuestasSena.OS_Guardar_Encuesta respuestas, object userState) {
            if ((this.onBeginGuardarRespuestasEncuestaDelegate == null)) {
                this.onBeginGuardarRespuestasEncuestaDelegate = new BeginOperationDelegate(this.OnBeginGuardarRespuestasEncuesta);
            }
            if ((this.onEndGuardarRespuestasEncuestaDelegate == null)) {
                this.onEndGuardarRespuestasEncuestaDelegate = new EndOperationDelegate(this.OnEndGuardarRespuestasEncuesta);
            }
            if ((this.onGuardarRespuestasEncuestaCompletedDelegate == null)) {
                this.onGuardarRespuestasEncuestaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGuardarRespuestasEncuestaCompleted);
            }
            base.InvokeAsync(this.onBeginGuardarRespuestasEncuestaDelegate, new object[] {
                        respuestas}, this.onEndGuardarRespuestasEncuestaDelegate, this.onGuardarRespuestasEncuestaCompletedDelegate, userState);
        }
    }
}
