PROCEDURE Pr_DarRptSistematizacion(p_idPeriodo      IN NUMBER,
                                     p_idUsuario      IN NUMBER,
                                     p_idFacilitador  IN NUMBER,
                                     p_idCoordinador  IN NUMBER,
                                     p_idGrupo        IN NUMBER,
                                     p_idDepartamento IN NUMBER,
                                     p_idMunicipio    IN NUMBER,
                                     p_fec_corte      IN varchar2,
                                     p_idInstrumento  IN NUMBER,
                                     p_resultado      OUT PK_UTILS.TY_CURSOR,
                                     p_codError       OUT NUMBER,
                                     p_msjError       OUT VARCHAR2);