INSERT INTO "HPV"."T10_OPCIONES" (A10CODIGO, A10NOMBRE, A10ORDEN, A10ESTADO) VALUES ('410', 'Lista de sistematización de experiencias', '32', 'A')
INSERT INTO "HPV"."T10_OPCIONES" (A10CODIGO, A10NOMBRE, A10ORDEN, A10ESTADO) VALUES ('411', 'Detalle sistematización de experiencias', '33', 'A')
INSERT INTO "HPV"."T10_OPCIONES" (A10CODIGO, A10NOMBRE, A10ORDEN, A10ESTADO) VALUES ('420', 'Admin lista sistematización', '34', 'A')
INSERT INTO "HPV"."T10_OPCIONES" (A10CODIGO, A10NOMBRE, A10ORDEN, A10ESTADO) VALUES ('421', 'Admin detalle sistematización', '35', 'A')

CREATE TABLE T64_SISTEMATIZACION 
(
  A64CODIGO NUMBER NOT NULL 
, A64PERIODO NUMBER 
, A64GRUPOFACILITADOR NUMBER 
, A64ESTADO CHAR(1) 
, A64FECHACREACION DATE 
, A64FECHAMODIFICACION DATE 
, A64USUARIOCREACION NUMBER 
, A64USUARIOMODIFICACION NUMBER 
, A64LINKVIDEO VARCHAR2(225) 
, A64FACILITADOR NUMBER 
, CONSTRAINT T64_SISTEMATIZACION_PK PRIMARY KEY 
  (
    A64CODIGO 
  )
  ENABLE 
);

COMMENT ON COLUMN T64_SISTEMATIZACION.A64CODIGO IS 'Identificacion del registro';

COMMENT ON COLUMN T64_SISTEMATIZACION.A64PERIODO IS 'Periodo';

COMMENT ON COLUMN T64_SISTEMATIZACION.A64GRUPOFACILITADOR IS 'Grupo facilitador';

COMMENT ON COLUMN T64_SISTEMATIZACION.A64ESTADO IS 'Estado';

COMMENT ON COLUMN T64_SISTEMATIZACION.A64FECHACREACION IS 'Fecha creacion';

COMMENT ON COLUMN T64_SISTEMATIZACION.A64FECHAMODIFICACION IS 'Fecha modificacion';

COMMENT ON COLUMN T64_SISTEMATIZACION.A64USUARIOCREACION IS 'Usuario creacion';

COMMENT ON COLUMN T64_SISTEMATIZACION.A64USUARIOMODIFICACION IS 'Usuario modificacion';

COMMENT ON COLUMN T64_SISTEMATIZACION.A64LINKVIDEO IS 'Link del video con la evidencia';

COMMENT ON COLUMN T64_SISTEMATIZACION.A64FACILITADOR IS 'Id del facilitador';

ALTER TABLE T64_SISTEMATIZACION 
ADD (A64INSTRUMENTO NUMBER );

COMMENT ON COLUMN T64_SISTEMATIZACION.A64INSTRUMENTO IS 'Id del instrumento correspondiente';

CREATE SEQUENCE T64_SISTEMATIZACION_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1;


CREATE TABLE T76_INSTRUMENTOSSIS 
(
  A76CODIGO NUMBER NOT NULL 
, A76NOMBRE VARCHAR2(225) NOT NULL 
, A76ESTADO CHAR(1) DEFAULT 'I' 
, A76FECHACREACION DATE 
, A76FECHAMODIFICACION DATE 
, A76USUARIOCREACION NUMBER 
, A76USUARIOMODIFICACION NUMBER 
, CONSTRAINT T76_INSTRUMENTOSSIS_PK PRIMARY KEY 
  (
    A76CODIGO 
  )
  ENABLE 
);

COMMENT ON COLUMN T76_INSTRUMENTOSSIS.A76CODIGO IS 'Identificador del registro';

COMMENT ON COLUMN T76_INSTRUMENTOSSIS.A76NOMBRE IS 'Nombre del instrumento';

COMMENT ON COLUMN T76_INSTRUMENTOSSIS.A76ESTADO IS 'A:Activo I:Inactivo';

COMMENT ON COLUMN T76_INSTRUMENTOSSIS.A76FECHACREACION IS 'Fecha de creacion';

COMMENT ON COLUMN T76_INSTRUMENTOSSIS.A76FECHAMODIFICACION IS 'Fecha de modificacion';

COMMENT ON COLUMN T76_INSTRUMENTOSSIS.A76USUARIOCREACION IS 'Usuario creacion';

COMMENT ON COLUMN T76_INSTRUMENTOSSIS.A76USUARIOMODIFICACION IS 'Usuario modificacion';


CREATE TABLE T77_ESTADOSSISTEMATIZACION 
(
  A77CODIGO CHAR(1) NOT NULL 
, A77NOMBRE VARCHAR2(50) 
, A77ESTADO CHAR(1) 
, A77FECHACREACION DATE 
, A77FECHAMODIFICACION DATE 
, A77USUARIOCREACION NUMBER 
, A77USUARIOMODIFICACION NUMBER 
, CONSTRAINT T77_ESTADOSSISTEMATIZACION_PK PRIMARY KEY 
  (
    A77CODIGO 
  )
  ENABLE 
);

COMMENT ON COLUMN T77_ESTADOSSISTEMATIZACION.A77CODIGO IS 'Identificacion del registro';

COMMENT ON COLUMN T77_ESTADOSSISTEMATIZACION.A77NOMBRE IS 'Nombre del estado';

COMMENT ON COLUMN T77_ESTADOSSISTEMATIZACION.A77ESTADO IS 'A:Activo I:Inactivo';

COMMENT ON COLUMN T77_ESTADOSSISTEMATIZACION.A77FECHACREACION IS 'Fecha de creacion';

COMMENT ON COLUMN T77_ESTADOSSISTEMATIZACION.A77FECHAMODIFICACION IS 'Fecha de modificacion';

COMMENT ON COLUMN T77_ESTADOSSISTEMATIZACION.A77USUARIOCREACION IS 'Usuario creacion';

COMMENT ON COLUMN T77_ESTADOSSISTEMATIZACION.A77USUARIOMODIFICACION IS 'Usuario modificacion';


INSERT INTO "HPV"."T77_ESTADOSSISTEMATIZACION" (A77CODIGO, A77NOMBRE, A77ESTADO) VALUES ('P', 'Pendiente de aprobación', 'A')
INSERT INTO "HPV"."T77_ESTADOSSISTEMATIZACION" (A77CODIGO, A77NOMBRE, A77ESTADO) VALUES ('A', 'Activo', 'A')
INSERT INTO "HPV"."T77_ESTADOSSISTEMATIZACION" (A77CODIGO, A77NOMBRE, A77ESTADO) VALUES ('I', 'Inactivo', 'A')
INSERT INTO "HPV"."T77_ESTADOSSISTEMATIZACION" (A77CODIGO, A77NOMBRE, A77ESTADO) VALUES ('R', 'Rechazado', 'A')
INSERT INTO "HPV"."T77_ESTADOSSISTEMATIZACION" (A77CODIGO, A77NOMBRE, A77ESTADO) VALUES ('S', 'Seleccionado', 'A')

INSERT INTO "HPV"."T76_INSTRUMENTOSSIS" (A76CODIGO, A76NOMBRE, A76ESTADO) VALUES ('1', 'Historias de vida', 'A')
INSERT INTO "HPV"."T76_INSTRUMENTOSSIS" (A76CODIGO, A76NOMBRE, A76ESTADO) VALUES ('2', 'Ejemplos de liderazgo', 'A')

INSERT INTO "HPV"."T95_MENSAJERESPUESTA" (A95CODIGO, A95MENSAJE, A95ESTADO) VALUES ('111', 'NO HAY INSTRUMENTOS DE SISTEMATIZACION REGISTRADOS', 'A')
INSERT INTO "HPV"."T95_MENSAJERESPUESTA" (A95CODIGO, A95MENSAJE, A95ESTADO) VALUES ('112', 'YA HAY UN INSTRUMENTO DE  SISTEMATIZACIÓN DEL MISMO TIPO, REGISTRADO PARA ESTE GRUPO', 'A')
