ALTER TABLE T64_SISTEMATIZACION RENAME COLUMN A64LINKVIDEO TO A64INSCRITO;

ALTER TABLE T64_SISTEMATIZACION  
MODIFY (A64INSCRITO NUMBER );

COMMENT ON COLUMN T64_SISTEMATIZACION.A64INSCRITO IS 'Id del inscrito seleccionado para este instrumento';

ALTER TABLE T64_SISTEMATIZACION 
ADD (A64MOTIVORECHAZO VARCHAR2(200) );

COMMENT ON COLUMN T64_SISTEMATIZACION.A64MOTIVORECHAZO IS 'Motivo del rechazo del instrumento';


INSERT INTO "HPV"."T10_OPCIONES" (A10CODIGO, A10NOMBRE, A10ORDEN, A10ESTADO) VALUES ('430', 'Super lista sistematización', '36', 'A')
INSERT INTO "HPV"."T10_OPCIONES" (A10CODIGO, A10NOMBRE, A10ORDEN, A10ESTADO) VALUES ('431', 'Super detalle sistematización', '37', 'A')

UPDATE "HPV"."T77_ESTADOSSISTEMATIZACION" SET A77NOMBRE = 'Aceptado por coordinador' WHERE A77CODIGO = 'A'

CREATE TABLE T116_RPT_SISTEMATIZACION 
(
  PERIODO VARCHAR2(50) 
, DIVIPOLA VARCHAR2(50) 
, NOMBRE_DEPARTAMENTO VARCHAR2(250) 
, NOMBRE_MUNICIPIO VARCHAR2(250) 
, SIGRA_GRUPO VARCHAR2(50) 
, CEDULA_FACILITADOR VARCHAR2(50) 
, NOMBRE_FACILITADOR VARCHAR2(250) 
, PRIMERNOMBRE_PARTICIPANTE VARCHAR2(250) 
, SEGUNDONOMBRE_PARTICIPANTE VARCHAR2(250) 
, PRIMERAPELLIDO_PARTICIPANTE VARCHAR2(250) 
, SEGUNDOAPELLIDO_PARTICIPANTE VARCHAR2(250) 
, GENERO VARCHAR2(20) 
, TIPO_DOCUMENTO_PARTICIPANTE VARCHAR2(50) 
, DOCUMENTO_PARTICIPANTE VARCHAR2(50) 
, CODIGO_BENEFICIARIO VARCHAR2(50) 
, RUTA_ARCHIVO VARCHAR2(250) 
);

COMMENT ON COLUMN T116_RPT_SISTEMATIZACION.PERIODO IS 'Período del instrumento';

COMMENT ON COLUMN T116_RPT_SISTEMATIZACION.DIVIPOLA IS 'Código de división política';

COMMENT ON COLUMN T116_RPT_SISTEMATIZACION.NOMBRE_DEPARTAMENTO IS 'Nombre del departamento del estudiante';

COMMENT ON COLUMN T116_RPT_SISTEMATIZACION.NOMBRE_MUNICIPIO IS 'Nombre del municipio';

COMMENT ON COLUMN T116_RPT_SISTEMATIZACION.SIGRA_GRUPO IS 'Sigla del grupo en el que se encontraba el participante al ser escogido';

COMMENT ON COLUMN T116_RPT_SISTEMATIZACION.CEDULA_FACILITADOR IS 'Cédula del facilitador';

COMMENT ON COLUMN T116_RPT_SISTEMATIZACION.NOMBRE_FACILITADOR IS 'Nombre del facilitador';

COMMENT ON COLUMN T116_RPT_SISTEMATIZACION.PRIMERNOMBRE_PARTICIPANTE IS 'Nombre del participante';

COMMENT ON COLUMN T116_RPT_SISTEMATIZACION.SEGUNDONOMBRE_PARTICIPANTE IS 'Segundo nombre del participante';

COMMENT ON COLUMN T116_RPT_SISTEMATIZACION.PRIMERAPELLIDO_PARTICIPANTE IS 'Primer apellido del participante';

COMMENT ON COLUMN T116_RPT_SISTEMATIZACION.SEGUNDOAPELLIDO_PARTICIPANTE IS 'Segundo apeliido del participante';

COMMENT ON COLUMN T116_RPT_SISTEMATIZACION.GENERO IS 'Género del participante';

COMMENT ON COLUMN T116_RPT_SISTEMATIZACION.TIPO_DOCUMENTO_PARTICIPANTE IS 'Tipo de documento del participante';

COMMENT ON COLUMN T116_RPT_SISTEMATIZACION.DOCUMENTO_PARTICIPANTE IS 'Documento del participante';

COMMENT ON COLUMN T116_RPT_SISTEMATIZACION.CODIGO_BENEFICIARIO IS 'Código del beneficiario';

COMMENT ON COLUMN T116_RPT_SISTEMATIZACION.RUTA_ARCHIVO IS 'Ruta del archivo';

ALTER TABLE T116_RPT_SISTEMATIZACION 
ADD (FEC_CORTE DATE );

COMMENT ON COLUMN T116_RPT_SISTEMATIZACION.FEC_CORTE IS 'Fecha de corte del reporte';

ALTER TABLE T116_RPT_SISTEMATIZACION RENAME COLUMN SIGRA_GRUPO TO SIGLA_GRUPO;

UPDATE "HPV"."T62_REPORTE" SET A62ESTADO = 'I' WHERE A62CODIGO = '6'
UPDATE "HPV"."T62_REPORTE" SET A62ESTADO = 'I' WHERE A62CODIGO = '7'
UPDATE "HPV"."T62_REPORTE" SET A62ESTADO = 'I' WHERE A62CODIGO = '8'
INSERT INTO "HPV"."T62_REPORTE" (A62CODIGO, A62CATEGORIA, A62NOMBRE, A62DESCRIPCION, A62URL, A62ESTADO) VALUES ('15', 'Sistematizacion experiencias', 'Sistematización', 'Reporte Sistematización de experiencias', '/Reportes/Sistematizacion/Sistematizacion.aspx', 'A')
