//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPV_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class T12DBC_PERIODOS
    {
        public decimal A12CODIGO { get; set; }
        public string A12NOMBRE { get; set; }
        public Nullable<System.DateTime> A12FECHAINICIO { get; set; }
        public Nullable<System.DateTime> A12FECHAFIN { get; set; }
        public string A12ESTADO { get; set; }
        public Nullable<System.DateTime> A12FECHACREACION { get; set; }
        public Nullable<System.DateTime> A12FECHAMODIFICACION { get; set; }
        public Nullable<decimal> A12NOPERIODO { get; set; }
        public Nullable<decimal> A12USUARIOCREACION { get; set; }
        public Nullable<decimal> A12USUARIOMODIFICACION { get; set; }
    }
}
